settings:
  legacy:
    force: false
    interval: 0s
server:
  status: true
  open: false
  port: 5002
  host: localhost
schema:
- name: セッション
  path: .
  commands:
    install:
      status: true
      method: go build -o go-team
    run:
      status: true
      method: ./go-team
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
